# action.yml
name: 'Install Snowflake CLI'
description: 'Download and install snowflake-cli-labs through PyPi'
inputs:
  cli_version:
    description: 'Snowcli version'
    required: false
  python_version:
    description: 'Python version'
    required: false
  venv_path:
    description: 'Virtual environment to be used'
    required: false
  config_file_path:
    description: 'Config file path'
    required: false
    default: './config.toml'
  save_config_file_in_snowflake_dir:
    description: 'Flag to indicate whether save the config file in snowflake path'
    required: false
    default: true

runs:
  using: 'composite'
  steps:
    - name: Download snowflake-cli-labs
      shell: bash
      run: bash $GITHUB_ACTION_PATH/install_snowcli.sh
      env:
        CLI_VERSION: ${{ inputs.cli_version }} 
        PYTHON_VERSION: ${{ inputs.python_version }} 
        VENV_PATH: ${{ inputs.venv_path }} 

    - name: Set up config.toml
      shell: bash
      run: bash $GITHUB_ACTION_PATH/setup_config_file.sh
      env:
        CONFIG_FILE_PATH: ${{ inputs.config_file_path }} 
        SAVE_CONFIG_FILE_SNOWFLAKE_DIR: ${{ inputs.save_config_file_in_snowflake_dir }} 