# action.yml
name: 'Install Snowflake CLI'
description: 'Download and install snowflake-cli-labs through PyPi'
inputs:
  cli_version:
    description: 'Snowcli version'
    required: false
    default: ''
  config_file_path:
    description: 'Config file path'
    required: false
    default: './config.toml'
  install_using_pipx:
    description: 'Flag to indicate whether install snowflake-cli-labs using pipx instead of pip '
    required: false
    default: false
  save_config_file_in_snowflake_dir:
    description: 'Flag to indicate whether save the config file in snowflake path'
    required: false
    default: false

runs:
  using: 'composite'
  steps:
    - name: Download snowflake-cli-labs
      shell: bash
      run: bash $GITHUB_ACTION_PATH/install_snowcli.sh
      env:
        CLI_VERSION: ${{ inputs.cli_version }} 
        INSTALL_USING_PIPX: ${{ inputs.install_using_pipx }} 

    - name: Set up config.toml
      shell: bash
      run: bash $GITHUB_ACTION_PATH/setup_config_file.sh
      env:
        CONFIG_FILE_PATH: ${{ inputs.config_file_path }} 
        SAVE_CONFIG_FILE_SNOWFLAKE_DIR: ${{ inputs.save_config_file_in_snowflake_dir }} 