# action.yml
name: 'Update NativeApp source code'
description: 'Updates the nativeapp source code in the application stage file'
inputs:
  config_file:
    description: 'SnowCli required config file'
    required: true
  stage_name:
    description: 'Stage where the code is going to be updated or deployed'
    required: true
  source_code_path:
    description: 'Path to the source code to be updated'
    required: false
    default: '.'
  snowcli_version:
    description: 'Snowcli version to be used'
    required: false
    default: ''
  python_version:
    description: 'Python version to be used'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'docker://jorge021/cache-testing'
  args:
    - ${{ inputs.config_file }}
    - ${{ inputs.stage_name }}
    - ${{ inputs.source_code_path }}
    - ${{ inputs.snowcli_version }}
    - ${{ inputs.python_version }}