# action.yml
name: 'Install Snowflake CLI'
description: 'Download and install snowflake-cli-labs through pipx'
inputs:
  cli-version:
    description: 'Snowflake CLI version'
    required: false
    default: ''

  default-config-file-path:
    required: false
    default: './config.toml'

runs:
  using: 'composite'
  steps:
    - name: Download snowflake-cli-labs ${{ inputs.cli_version }}
      shell: bash
      run: bash scripts/install_snowcli.sh
      env:
        CLI_VERSION: ${{ inputs.cli-version }} 

    - name: Set up config.toml
      shell: bash
      run: bash scripts/setup_config_file.sh
      env:
        CONFIG_FILE_PATH: ${{ inputs.default-config-file-path }} 