default_connection_name = "myconnection"

[connections.myconnection]
account = "fxb32936"
user = "jorvasquezr"
password = ""
warehouse = "COMPUTE_WH"
database = "mytestdb"
schema = "PUBLIC"
role = "ACCOUNTADMIN"
region = "us-east-1"

