name: connect-to-snowflake-account-test

on: [push]

jobs:
  connect-to-snowflake-account-test:
      runs-on: ${{ matrix.os }}

      strategy:
        fail-fast: false
        matrix:
          os:
            - macos-latest
            - ubuntu-latest
            - windows-latest

      env:
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}

      name: Install Snowflake CLI in ${{ matrix.os }}
      steps:
        - name: create temporal config file.
          run: touch config.toml
          
        - name: Set up Snowflake CLI
          uses: ./ 
          id: setup_snowcli
          with:
            cli-version: '2.1.0'

        - name: Test connection 
          shell: bash
          run: |
            snow --version
            snow connection list
            snow connection test