on:
  push:
    branches:
      - main
      - composite_snowcli_action_deploy

name: Upload Release Assets

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.SECRET_GITHUB_TOKEN }} 