name: install-snowcli-with-pip-and-then-with-pipx

on: [push]

jobs:

  install-snowcli-with-pip-and-then-with-pipx:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    env:
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}

    name: Install Snowflake CLI in ${{ matrix.os }} with pip and pipx
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Snowflake CLI with pip
        run: python -m pip install snowflake-cli-labs

      - name: Install Snowflake CLI with pipx
        uses: ./ 
        id: setup_snowcli
        with:
          default-config-file-path: '.github/workflows/tests-files/config.toml'
          
      - name: Test snow installation
        shell: bash
        run: |
          current_path=$(which snow)
          snow_expected_path="$PIPX_BIN_DIR/snow_pipx_path/snow"
          if [[ $RUNNER_OS = "Windows" ]]; then 
              snow_expected_path="/c/Program Files (x86)/pipx_bin/snow_pipx_path/snow"
          fi

          if [[ "$current_path" != "$snow_expected_path" ]]
          then
              echo "Using snow installed in $current_path, should be the version installed in $snow_expected_path"
              exit 1
          fi
          