name: connect-to-snowflake-account-test

on:
  push:
    branches:
      - '*' 
  schedule:
    - cron: "0 0 * * *"  

jobs:
  connect-to-snowflake-account-test:
      runs-on: ${{ matrix.os }}

      strategy:
        fail-fast: false
        matrix:
          os:
            - macos-latest
            - ubuntu-latest
            - windows-latest

      env:
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}

      name: Install Snowflake CLI in ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v4
        - name: Set up Snowflake CLI
          uses: ./ 
          id: setup_snowcli
          with:
            default-config-file-path: '.github/workflows/tests-files/config.toml'

        - name: Test connection 
          shell: bash
          run: |
            snow --version
            snow connection list
