name: connect-to-snowflake-account-test

on:
  push:
    branches:
      - '*' 
  schedule:
    - cron: "0 0 * * *"  

jobs:
  connect-to-snowflake-account-test:
      runs-on: ${{ matrix.os }}

      strategy:
        fail-fast: false
        matrix:
          os:
            - macos-latest
            - ubuntu-latest
            - windows-latest

      name: Install Snowflake CLI in ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v4
          with:
            persist-credentials: false

        - name: Set up Snowflake CLI
          uses: ./ 
          id: setup_snowcli
          with:
            default-config-file-path: '.github/workflows/tests-files/config.toml'

        - name: Test connection 
          env:
            SNOWFLAKE_CONNECTIONS_MYCONNECTION_PASSWORD: 'password'
            SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT: 'account'
          shell: bash
          
          run: |
            snow --version
            snow connection list

