name: test

on: [push]

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: jorge021/cache-testing
          cache-from: type=gha
          cache-to: type=gha,mode=max

  action_with_config_file:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_PASSWORD: ${{ secrets.SNOWFLAKE_CONNECTIONS_MYCONNECTION_PASSWORD }}

    name: Job to test the connection with snowflake
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload source code to Snowflake
        uses: ./ 
        id: upload_source_code
        with:
          config_file: "/action/workspace/config.toml"
          stage_name: "@snowflake_example_stage"
          source_code_path: "./example_native_app_source_code"
#      - name: Show execution log
#        run: echo "$LOG_SNOWCLI_STAGE_UPDATE"