name: tests

on: [push]

jobs:

  install_Snowcli_with_pip_and_then_with_pipx:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

      SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}

    name: Test the installation of Snowflake CLI with pip and then with pipx
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Snowflake CLI 2.1.1 with pip
        run: python -m pip install snowflake-cli-labs==2.1.1 

      - name: Install Snowflake CLI 2.1.0 with pipx
        uses: ./ 
        id: setup_snowcli
        with:
          cli-version: '2.1.0'

      - name: Test version
        run: snow --version

  install_Snowcli_with_pipx_and_then_with_pip:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_CONNECTIONS_MOBILIZE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

    name: Test the installation of Snowflake CLI with pipx and then with pip
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Snowflake CLI 2.1.0 with pipx
        uses: ./ 
        id: setup_snowcli
        with:
          cli-version: '2.1.0'

      - name: Show snow installation 2.1.0
        run: |
          snow --version
          which snow
  
      - name: Install Snowflake CLI 2.1.1 with pip
        run: python -m pip install snowflake-cli-labs==2.1.1
      - name: Show snow installation 2.1.1
        run: |
          snow --version
          which snow 
          
  install_in_multiple_os:
      runs-on: ${{ matrix.os }}

      strategy:
        fail-fast: false
        matrix:
          os:
            - macos-latest
            - ubuntu-latest
            - windows-latest

      env:
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_PASSWORD: ${{ secrets.SNOWFLAKE_CONNECTIONS_MYCONNECTION_PASSWORD }}

      name: Test install Snowflake CLI in multiple OS
      steps:
        - uses: actions/checkout@v4
        - name: Set up Snowflake CLI
          uses: ./ 
          id: setup_snowcli
          with:
            cli-version: '2.1.0'

        - name: Test version
          run: snow --version

        - name: Test connection 
          shell: bash
          run: |
            snow connection list
            snow connection test

  deploy_demo_native_app:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_PASSWORD: ${{ secrets.SNOWFLAKE_CONNECTIONS_MYCONNECTION_PASSWORD }}
    name: Deploys the app defined in my_app folder in the Snowflake account
    steps:
      - uses: actions/checkout@v4
      - name: Set up Snowflake CLI
        uses: ./ 
        id: setup_snowcli
        with:
          cli-version: '2.1.0'
      - name: Test for Deploy
        run: |
          cd my_app
          snow app version create V1
          snow app run --version V1 