name: test_using_two_snowcli_versions

on: [push]

jobs:
  action_with_config_file:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_CONNECTIONS_MOBILIZE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

    name: Job to test the connection with snowflake
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install snowcli 2.1.1
        run: python -m pip install snowflake-cli-labs==2.1.1 

      - name: Set up snowcli 2.1.0
        uses: ./ 
        id: setup_snowcli
        with:
          cli_version: '2.1.0'
          install_using_pipx: true

      - name: Test version
        run: snow --version

      - name: Test connection 
        shell: bash
        run: |
          snow connection list
          snow connection test

      - name: Test stage copy command
        shell: bash
        run: |
          if [[ ! $RUNNER_OS = "Windows" ]]; then 
            snow object stage copy --overwrite example_native_app_source_code/ @snowflake_example_stage 
          else 
            snow object stage copy example_native_app_source_code/ @snowflake_example_stage --overwrite
          fi
          
          snow object stage list @snowflake_example_stage
        