name: set-unboud-pipx-variable-test
on:
    schedule:
      - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
  set-unboud-pipx-variable-test:
      runs-on: ${{ matrix.os }}

      strategy:
        fail-fast: false
        matrix:
          os:
            - macos-latest
            - ubuntu-latest
            - windows-latest

      env:
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        PIPX_BIN_DIR: null

      name: Install Snowflake CLI in ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v4
        - name: Set up Snowflake CLI
          uses: ./ 
          id: setup_snowcli
          with:
            cli-version: '2.1.0'
            default-config-file-path: '.github/workflows/tests-files/config.toml'

        - name: Test connection 
          shell: bash
          run: |
            snow --version
            snow connection list