
  name: test

on: [push]

jobs:
  action_with_config_file:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    env:
      SNOWFLAKE_CONNECTION: "${{secrets.SNOWFLAKE_CONNECTION}}"
      SNOWFLAKE_CONNECTIONS_MOBILIZE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

    name: Job to test the connection with snowflake
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload source code to Snowflake
        uses: ./ 
        id: upload_source_code
        with:
          config_file: "${{secrets.SNOWFLAKE_CONNECTION}}"
          stage_name: "@snowflake_example_stage"
          source_code_path: "./example_native_app_source_code"
#      - name: Show execution log
#        run: echo "$LOG_SNOWCLI_STAGE_UPDATE"